# Generated by Django 3.2.13 on 2022-07-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmovie',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movieimg',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
