# Generated by Django 3.2.13 on 2022-07-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_aboutmovie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmovie',
            name='image',
            field=models.ManyToManyField(related_name='image', to='base.movieimg'),
        ),
    ]
