# Generated by Django 3.2.13 on 2022-07-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_aboutmovie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmovie',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
